export const styles = {
    panelHeader: {
        background: "rgba(24, 33, 51, 0.95)",
        padding: "10rem 10rem 10rem",
    } as const,
    panelBody: {
        background: "rgba(42, 56, 84, 0.88)",
        padding: "8rem 0rem 10rem 10rem",
        display: "flex",
        flexDirection: "column",
        flex: 1,
        minHeight: 0,
    } as const,
    listArea: {
        flex: 1,
        minHeight: 0,
    } as const,
    areasToggleRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        cursor: "pointer",
        paddingTop: "8rem",
        paddingRight: "10rem",
        paddingBottom: "8rem",
    } as const,
    divider: {
        height: "1rem",
        background: "rgba(255,255,255,0.15)",
        marginRight: "10rem",
        marginTop: "8rem",
        marginBottom: "8rem",
    } as const,
    memberList: {} as const,
    row: { display: "flex", alignItems: "center", margin: "3rem 0" } as const,
    smallButton: {
        background: "rgba(255,255,255,0.15)",
        color: "white",
        borderRadius: "3rem",
        padding: "2rem 8rem",
        margin: "2rem 2rem",
    } as const,
    dangerButton: {
        color: "white",
        borderRadius: "3rem",
        padding: "2rem 8rem",
        margin: "2rem 2rem",
    } as const,
    headerRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
    } as const,
    header: {
        color: "rgb(75, 195, 241)",
        fontSize: "16rem",
        textTransform: "uppercase",
        letterSpacing: "1rem",
    } as const,
    newGroupButton: {
        color: "white",
        borderRadius: "3rem",
        padding: "2rem 10rem",
        marginRight: "6rem",
        fontWeight: "bold",
    } as const,
    subtle: { color: "rgba(255,255,255,0.6)" } as const,
    groupCard: {
        background: "rgba(0,0,0,0.25)",
        borderRadius: "var(--panelRadius)",
        padding: "6rem",
        margin: "3rem 0",
    } as const,
}
