// Color-valued vanilla CSS variables only (skips radius/opacity/font-size/
// spacing scalars) - see the "reference_cs2_vanilla_css_variables" memory for
// the full catalog this was pulled from, including how it was extracted.
export interface ColorTokenGroup {
    label: string
    tokens: string[]
}

export const colorTokenGroups: ColorTokenGroup[] = [
    {
        label: "Panel chrome",
        tokens: [
            "--panelColorNormal",
            "--panelColorDark",
            "--panelColorDark-hover",
            "--panelColorDark-active",
            "--pausePanelColorDark",
            "--sectionHeaderColor",
            "--sectionHeaderColorLight",
            "--sectionHeaderLockedColor",
            "--sectionBackgroundColor",
            "--sectionBackgroundColorLight",
            "--sectionBackgroundLockedColor",
            "--sectionBorderColor",
            "--dividerColor",
            "--dividerColorInverted",
            "--tooltipColor",
        ],
    },
    {
        label: "Interactive states",
        tokens: [
            "--hoverColor",
            "--hoverColorNormal",
            "--hoverColorBright",
            "--hoverColorDark",
            "--activeColor",
            "--activeColorNormal",
            "--activeColorBright",
            "--activeColorDark",
            "--disabledColor",
            "--focusedColor",
            "--focusedColorDark",
            "--selectedColor",
            "--selectedColorDark",
            "--selectedColor-hover",
            "--selectedColor-active",
            "--selectableColor-hover",
        ],
    },
    {
        label: "Accent / semantic",
        tokens: [
            "--accentColorNormal",
            "--accentColorNormal-hover",
            "--accentColorNormal-pressed",
            "--accentColorLight",
            "--accentColorLighter",
            "--accentColorLightest",
            "--accentColorDark",
            "--accentColorDark-hover",
            "--accentColorDark-pressed",
            "--accentColorDark-focused",
            "--accentColorDarker",
            "--accentColorDarker-hover",
            "--accentColorDarker-pressed",
            "--positiveColor",
            "--warningColor",
            "--negativeColor",
            "--neutralColor",
            "--lockedColor",
            "--unlockedColor",
            "--linkColor",
        ],
    },
    {
        label: "Text colors",
        tokens: [
            "--textColor",
            "--textColorDim",
            "--textColorDimmer",
            "--textColorDimmest",
            "--textColorDark",
            "--textColorDarkDim",
            "--textColorDarkDimmer",
            "--textColorDarkDimmest",
            "--textColorHighlight",
            "--textColorDisabled",
            "--textColorLocked",
            "--focusedTextColor",
            "--focusedTextColorDark",
            "--selectedTextColor",
            "--selectedTextColorDark",
        ],
    },
    {
        label: "Dialog buttons",
        tokens: [
            "--dialogButtonYesColor",
            "--dialogButtonYesColor-hover",
            "--dialogButtonYesColor-active",
            "--dialogButtonYesColor-focused",
            "--dialogButtonNoColor",
            "--dialogButtonNoColor-hover",
            "--dialogButtonNoColor-active",
            "--dialogButtonNoColor-focused",
        ],
    },
    {
        label: "Common palette",
        tokens: [
            "--commonBlack",
            "--commonDarkBlue",
            "--commonWhite",
            "--commonLightGrey",
            "--commonCyan",
            "--commonGray",
            "--commonTransparentGray",
            "--highlightBrightBlue",
            "--highlightLightBlue",
            "--highlightWarningRed",
            "--highlightWarningLightRed",
            "--highlightGreen",
            "--highlightYellow",
        ],
    },
    {
        label: "Toolbar / menu",
        tokens: [
            "--toolbarButtonColor",
            "--toolbarButtonColor-hover",
            "--toolbarButtonColor-pressed",
            "--toolbarButtonColor-disabled",
            "--toolbarFieldColor",
            "--toolbarFieldColor-hover",
            "--toolbarFieldColor-active",
            "--toolbarFieldBorderColor",
            "--panelButtonColor",
            "--panelButtonColor-hover",
            "--panelButtonColor-active",
            "--panelButtonColor-focused",
            "--menuHoverColor",
            "--menuActiveColor",
            "--menuFocusedColor",
            "--menuSelectedColor",
            "--menuDisabledColor",
            "--menuBorderColor1",
            "--menuBorderColor2",
            "--menuPanel1",
            "--menuPanel2",
            "--menuPanel3",
        ],
    },
]
